#!/usr/bin/env bash

checkmark="\xe2\x98\x91"
cross="\xe2\x98\x92"

startred='\033[0;31m'
endcolor='\033[0m'
startgreen='\033[0;32m'

echob() {
  echo -e "\033[1m$1\033[0m"
}

echoCheck() {
  echo -e "$startgreen $checkmark $1 $endcolor"
}

echoError() {
  echo -e "$startred $cross $1 $endcolor"
}

dtf() {
  pushd "$1" > /dev/null
    shift
    terraform $@
  popd > /dev/null
}

check() { # checks is a tool is working
  if ! type "$1" > /dev/null 2>&1; then
    echoError "$2"
    exit 1
  else
    echoCheck "$3"
  fi
}

goal_prepare() {
  check "terraform" "Terraform not installed!" "Terraform available"
  dtf init init
  dtf init apply
  dtf infra init
}

goal_fmt() {
  terraform fmt
}

goal_dev() {
  exec_goal dev "$@"
}

goal_prod() {
  exec_goal prod "$@"
}

exec_goal() {
  VARS=""
  ENV=${1}
  shift
  CMD=${1}
  shift
  if [[ "$CMD" != "output" ]]; then
    VARS="-var-file=env/dev.tfvars"
  fi
  TF_WORKSPACE=dev dtf infra ${CMD} ${VARS} "$@"
}

goal_shuttle() {
  BASTION=`./tfw ${1} output bastion_ip`
  CIDR=`awk '/cidr/{gsub("\"","");print $3}' infra/env/${1}.tfvars`
  shift
  sshuttle -v -e "ssh -i infra/keys/id_rsa" -r ec2-user@${BASTION} "${CIDR%%[[:cntrl:]]}" "$@"
}

if type -t "goal_$1" &>/dev/null; then
  goal_$1 ${@:2}
else
  echo "usage: $0 <goal>

goal:
    prepare                  -- make sure everything is set up correctly so this project can actually work
    dev <commands>           -- work on dev
    prod <commands>          -- work on prod
    shuttle <env>
"
  exit 1
fi
