version: 2

terraform: &terraform
  docker:
    - image: hashicorp/terraform:full
  working_directory: /tmp/workspace/tm

jobs:
  validate:
    <<: *terraform
    steps:
      - checkout
      - run:
          name: Prepare
          command: ./tfw prepare
      - persist_to_workspace:
          root: .
          paths: .

workflows:
  version: 2
  build:
    jobs:
      - validate
