version: 2

general:
  branches:
    only:
     - master
     - devel

base_image: &base_image
  hashicorp/terraform:full

working_directory: &working_directory
  ~/ws

default_config: &default_config
  docker:
    - image: *base_image
  working_directory: *working_directory
  environment:
    BASH_ENV: /root/.bashrc

repo_cache_key: &repo_cache_key
  tm-repo-{{ .Branch }}-{{ .Revision }}

restore_repo: &restore_repo
  restore_cache:
    key: *repo_cache_key

save_repo: &save_repo
  save_cache:
    key: *repo_cache_key
    paths:
      - *working_directory

set_terraform_environment: &set_terraform_environment
  run:
    name: Set Terraform environment
    command: |
      cd && touch $BASH_ENV
      if [ "${CIRCLE_BRANCH}" == "master" ]; then
        echo 'export TF_ENV=prod' >> $BASH_ENV
      else
        echo 'export TF_ENV=dev' >> $BASH_ENV
      fi

terraform_init: &terraform_init
  run:
    name: Terraform init
    command: |
      source $BASH_ENV
      ./tfw ${TF_ENV} init -input=false

apply_job: &apply_job
  <<: *default_config
  steps:
    - *restore_repo
    - *set_terraform_environment
    - *terraform_init
    - attach_workspace:
        at: *working_directory
    - run:
        name: Terraform apply
        command: |
          source $BASH_ENV
          if [[ -f plan/${TF_ENV}-tf.plan ]]; then
            ./tfw ${TF_ENV} apply -input=false --auto-approve plan/${TF_ENV}-tf.plan
          fi
          echo "No plan generated, skipping.."

jobs:

  build:
    <<: *default_config
    steps:
      - checkout
      - *set_terraform_environment
      - run:
          name: Terraform fmt
          command: |
            source $BASH_ENV
            if [ $(./tfw fmt | grep -v .terraform | tee fmt_result.txt | wc -l) -gt 0 ]; then
              echo "Format of this terraform files is not appropiate:"
              echo
              cat fmt_result.txt
              rm fmt_result.txt
              git checkout -- .
              echo
              echo "Please run terraform fmt and commit again"
              exit 1
            fi
      - *save_repo

  plan:
    <<: *default_config
    steps:
      - *restore_repo
      - *set_terraform_environment
      - *terraform_init
      - run:
          name: Terraform plan
          command: |
            source $BASH_ENV
            mkdir -p plan
            DIR=`pwd`
            ./tfw ${TF_ENV} plan -input=false -out=${DIR}/plan/${TF_ENV}-tf.plan
      - persist_to_workspace:
          root: *working_directory
          paths:
            - plan

  apply:
    <<: *apply_job

  apply-with-approval:
    <<: *apply_job

workflows:
  version: 2
  infrastructure:
    jobs:
      - build
      - plan:
          requires:
            - build
      - approve:
          type: approval
          requires:
            - plan
          filters:
            branches:
              only: master
      - apply-with-approval:
          requires:
            - approve
          filters:
            branches:
              only: master
      - apply:
          requires:
            - plan
          filters:
            branches:
              only: devel
